# HUMAN READABLE CONSTANTS
KILOBYTE: int = 1024
MEGABYTE: int = KILOBYTE * 1024
GIGABYTE: int = MEGABYTE * 1024
# ADDITIONAL CONSTANTS
FILE_SIZE_THRESHOLD: int = 3 * MEGABYTE
FILE_GLOB: str = r"*.*/"
EMPTY_DIR_GLOB: str = r"*"
ARCHIVER_PATH: str = r"C:\Portable Program Files\7zr.exe"
